# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "aha-parser"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "aha-parser"
region = "eu-central-1"
profile = "846581533651_AWSAdministratorAccess"
parameter_overrides = "Regions=\"eu-central-1\" AccountIDs=\"None\" EventSearchBack=\"1\" FromEmail=\"lpantaleo@tai.it\" ToEmail=\"lpantaleo@tai.it\" Subject=\"AWS Health Alert\" S3Bucket=\"bkt-aha-repo-e1\" AWSHealthEventType=\"issue | accountNotification | scheduledChange\""
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
