# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "aha-parser"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "cfn-aha-e0"
region = "eu-central-1"
profile = "258540651493_AWSAdministratorAccess"
parameter_overrides = "FromEmail=\"TD.BOTAWSMailDispatcher@fastweb.it,TD.AWSTrustedAdvisor@fastweb.it\" ToEmail=\"TD.BOTAWSMailDispatcher@fastweb.it,TD.AWSTrustedAdvisor@fastweb.it,lpantaleo@tai.it\" Subject=\"AWS Health Alert\" AssumeRoleArn=\"arn:aws:iam::276209787992:role/rle-aha-cross-account-access-e0\" EventSearchBack=\"1\" Regions=\"eu-central-1,eu-south-1\" AWSHealthEventType=\"issue | accountNotification | scheduledChange\" InScopeOus=\"ou-37bl-nuoyhcb5,ou-37bl-b7dao3w9\""
image_repositories = []
stack_name = "cfn-aha-e0"

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
